feat: add piece moves on current player's turn validation
chessio-eu/chessio-backend pull request #6
Opened 2024-03-23 13:46 UTC by castawaypirate

Test's and validator's messages may need to be reviewed.

2024-03-24 16:19 UTC, maliouris commented
![](https://github.trello.services/images/mini-trello-icon.png) [When a piece is going to move validate that its current player's turn](https://trello.com/c/8t2q8B3R/3-when-a-piece-is-going-to-move-validate-that-its-current-players-turn)

2024-03-24 16:54 UTC, maliouris requested changes

2024-03-24 16:54 UTC, maliouris commented on app/Http/Requests/MovePieceRequest.php
> +                if ($this->piece->game->playerTurn()->id !== app(CurrentPlayer::class)->get()->id) {
```suggestion
                if ($this->piece->game->playerTurn()->id !== $this->piece->player->id) {
```

2024-03-24 17:06 UTC, maliouris requested changes

2024-03-24 17:06 UTC, maliouris commented on tests/Unit/Http/Requests/MovePieceRequestTest.php
Add two properties for white and black piece and remove `$game` property from the class
```php
protected Piece $whitePiece;
protected Piece $blackPiece;
```

In the setup function initialize `$whitePiece` and `$blackPiece` and remove `$blackPiece` initialization from every test

In order for the last test to execute properly after the changes replace `$whitePlayer` with `$blackPlayer`

2024-03-25 14:18 UTC, maliouris requested changes

2024-03-25 14:18 UTC, maliouris commented on app/Models/Piece.php
> +
After the rebase onto main branch you do no longer need those lines
```suggestion
```

2024-03-30 14:42 UTC, castawaypirate commented
Requested changes have been made. Waiting @maliouris to review.

2024-04-20 15:22 UTC, maliouris approved these changes

2024-04-20 15:22 UTC, merged